// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentAssesment1;

#nullable disable

namespace StudentAssesment1.Migrations
{
    [DbContext(typeof(StudentAssesmentDbContext))]
    [Migration("20230906231312_DB3")]
    partial class DB3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtistSong", b =>
                {
                    b.Property<int>("ArtistsId")
                        .HasColumnType("integer");

                    b.Property<int>("SongsId")
                        .HasColumnType("integer");

                    b.HasKey("ArtistsId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("ArtistSong");
                });

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.Property<int>("GeneresId")
                        .HasColumnType("integer");

                    b.Property<int>("SongsId")
                        .HasColumnType("integer");

                    b.HasKey("GeneresId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("GenreSong");
                });

            modelBuilder.Entity("StudentAssesment1.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 53,
                            Bio = "Shawn Corey Carter, known professionally as Jay-Z, is an American rapper, record producer, and entrepreneur. Often regarded as the greatest rapper of all time, he has been central to the creative and commercial success of artists including Kanye West, Rihanna, and J. Cole.",
                            Name = "Jay-z"
                        },
                        new
                        {
                            Id = 2,
                            Age = 44,
                            Bio = "Marvin Pentz Gay Jr., known professionally as Marvin Gaye, was an American R&B and soul singer and songwriter",
                            Name = "Marvin Gaye"
                        },
                        new
                        {
                            Id = 3,
                            Age = 82,
                            Bio = "Parliament-Funkadelic is an American music collective of rotating musicians headed by George Clinton, primarily consisting of the funk bands Parliament and Funkadelic, both active since the 1960s",
                            Name = "Parliament-Funkadelic"
                        },
                        new
                        {
                            Id = 4,
                            Age = 36,
                            Bio = "Robert Nesta Marley OM was a Jamaican singer, musician, and songwriter. Considered one of the pioneers of reggae, his musical career was marked by fusing elements of reggae, ska, and rocksteady, as well as his distinctive vocal and songwriting style.",
                            Name = "Bob Marley"
                        },
                        new
                        {
                            Id = 5,
                            Age = 65,
                            Bio = "Miles Dewey Davis III was an American jazz musician, trumpeter, bandleader, and composer. He is among the most influential and acclaimed figures in the history of jazz and 20th-century music.",
                            Name = "Myles davis"
                        });
                });

            modelBuilder.Entity("StudentAssesment1.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hip-Hop"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Rhythm and blues"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Funk"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Reggae"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Jazz"
                        });
                });

            modelBuilder.Entity("StudentAssesment1.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArtistsId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Length")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Blueprint",
                            ArtistsId = 1,
                            Length = new DateTime(2023, 4, 20, 0, 3, 45, 0, DateTimeKind.Unspecified),
                            Title = "Takeover"
                        },
                        new
                        {
                            Id = 2,
                            Album = "Lets Get It On",
                            ArtistsId = 2,
                            Length = new DateTime(2023, 5, 2, 0, 4, 15, 0, DateTimeKind.Unspecified),
                            Title = "Lets Get It On"
                        },
                        new
                        {
                            Id = 3,
                            Album = "Computer Games",
                            ArtistsId = 3,
                            Length = new DateTime(2023, 6, 30, 0, 5, 20, 0, DateTimeKind.Unspecified),
                            Title = "Atomic Dog"
                        },
                        new
                        {
                            Id = 4,
                            Album = "Confrontation",
                            ArtistsId = 4,
                            Length = new DateTime(2023, 2, 20, 0, 3, 10, 0, DateTimeKind.Unspecified),
                            Title = "Buffalo Soldier"
                        },
                        new
                        {
                            Id = 5,
                            Album = "Round About Midnight",
                            ArtistsId = 5,
                            Length = new DateTime(2023, 1, 28, 0, 2, 45, 0, DateTimeKind.Unspecified),
                            Title = "Bye Bye Blackbird"
                        });
                });

            modelBuilder.Entity("StudentAssesment1.Models.SongGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SongGenres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 1,
                            SongId = 1
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 2,
                            SongId = 2
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 3,
                            SongId = 3
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 4,
                            SongId = 4
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 5,
                            SongId = 5
                        });
                });

            modelBuilder.Entity("ArtistSong", b =>
                {
                    b.HasOne("StudentAssesment1.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentAssesment1.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.HasOne("StudentAssesment1.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GeneresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentAssesment1.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
